server:
  port: 84

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ae5c422a-5790-4a0a-9e7a-dd7b590f09fd
        group: DEFAULT_GROUP